<a href="https://colab.research.google.com/github/baraalmasri/TF_Files/blob/master/neuralNetwork_moethod2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
 import numpy as np 
 

In [0]:
class Neural_Network(object):
  def __init__(self):
     #parameters 
     self.outputSize=1
     self.inputSize=2
     self.hiddenSize=3

     #weights (agirliklari ) Q0 +Q1x1 +Q2x2 + ...+ Qnxn
     self.w1=np.random.randn(self.inputSize ,self.hiddenSize)
     #print(self.w1)
     self.w2=np.random.rand(self.hiddenSize,self.outputSize)
     #print(self.w2)

      # ileri iterasyon 
  def forward(self,x):
       self.z =np.dot(x,self.w1)        # w11*x1 , w12*x2 ...w1n*xn
       self.z2 =self.sigmoid(self.z)    #  1 / (1+ e ^-(wi*xi) )
       self.z3=np.dot(self.z2,self.w2)  #  1 / (1+ e ^-(wi*xi) ) * W21 , 1 / (1+ e ^(wi*xi) ) * W22 ,1 / (1+ e ^(wi*xi) ) * W2n 
       o = self.sigmoid(self.z3)        #final activation function 
       return o 

       #sigmoid fonk.
  def sigmoid (self,s):
      return 1/(1+np.exp(-s))
    
    #sigmoid turevi
  def sigmoidPrime(self,s):
      return s*(1-s)   # derivative of sigmoid 
     
     # agirliklari  geri duzeltme yontemi 
  def backward(self,x,y,o):
      self.o_error= o 
      self.o_delta= self.o_error * self.sigmoidPrime(o)
      self.z2_error= self.o_delta.dot(self.w2.T)
      self.z2_delta =self.z2_error * self.sigmoidPrime(self.z2)
      self.w1 = self.w1 + x.T.dot(self.z2_delta)
      self.w2 = self.z2.T.dot (self.o_delta)
      
      #egitme 
  def train(self,x,y):
      o= self.forward(x)
      self.backward(x,y,o)

      #agirligi kayidet 
  def saveWeights(self):
     np.savetxt("w1.txt",self.w1 ,fmt ="%s")
     np.savetxt("w2.txt",self.w2, fmt ="%s")

  #tahmin et  
  def predict (self):
    print("predicted data based on trained weights: ")
    print ("input (scaled): \n"+ str(xPredicted))
    print("output : \n" + str(self.forward(xPredicted)))



In [0]:
#x = (hours studying m hours sleeping ) ,y = scare on test , xpredicted = 4 hours studying 
x=np.array(([2,9],[1,5],[3,6]),dtype=float )
y=np.array(([92],[86],[89]),dtype =float)
xPredicted = np.array(([4,8]),dtype=float)

#scale units 
#print(x)
x= x/np.amax(x,axis=0)
#print(x)

#print(xPredicted)
xPredicted = xPredicted /np.max(xPredicted ,axis = 0)  #maximum of xPredicted ( our input data)

y=y/100 # max test care is 100



In [0]:
NN= Neural_Network()

for i in range(10):
  print("# "+str(i) + "\n")
  print("input (scaled): \n" + str(x))
  print("actual output: \n"+str(y))
  print("Predicted output: \n"+ str(NN.forward(x)))
  print("Loss : \n"+ str(np.mean(np.square(y-NN.forward(x))))) # mean sum squared loss #hata ver'yor 
  print("\n")
  NN.train (x,y)


NN.saveWeights()
NN.predict()


# 0

input (scaled): 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
actual output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted output: 
[[0.71906377]
 [0.6957245 ]
 [0.72123816]]
Loss : 
0.03194745606725852


# 1

input (scaled): 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
actual output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted output: 
[[0.64102953]
 [0.62394514]
 [0.64807044]]
Loss : 
0.06402544390600069


# 2

input (scaled): 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
actual output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted output: 
[[0.64415287]
 [0.62664418]
 [0.65109083]]
Loss : 
0.0625413901292345


# 3

input (scaled): 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
actual output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted output: 
[[0.6456567 ]
 [0.62790472]
 [0.6524557 ]]
Loss : 
0.06185325293890446


# 4

input (scaled): 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1. 